version: '3.8'

services:
  db:
    container_name: ntt-postgres
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - 5433:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
